sudo: false
language: php

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: nightly

## Install or update dependencies
install:
  - composer validate
  - composer install
  - composer why-not phpunit/phpunit
  - composer show

## Run the actual test
script:
  - if [ -z "$qaExtended" ]; then make ci; fi;
  - if [ "$qaExtended" = "true" ]; then make ci-extended; fi;
